services:
  - type: web
    name: neurodermai-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: HF_MODEL_ID
        value: Jayanth2002/dinov2-base-finetuned-SkinDisease
      - key: HF_TOKEN
        sync: false
      - key: CORS_ORIGINS
        sync: false
      - key: JWT_SECRET
        generateValue: true
